version: "3.9"

services:
  ros2:
    image: utsarobotics/ros2-humble:1.0.0
    container_name: ros2-servo
    command: bash
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    group_add:
      - dialout
    environment:
      - QT_QPA_PLATFORM=wayland
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
    volumes:
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
      - ~/ros2_ws:/root/ros2_ws
    stdin_open: true
    tty: true
    restart: "no"

